[package]
name = "wv"
version = "0.1.0"
edition = "2021"

[lib]
name = "wv"
crate-type = ["rlib", "staticlib"]

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.142"
scryer-prolog = "0.9.4"
multimap = "0.10.1"

[build-dependencies]
cbindgen = "0.29.0"